Repository Alwatr/weaver-starter-kit, pull requests merged in 2024-10, with the labels that each got.

#158 feat(alwatr): add `alwatr` package as a reference to import the main packages
  .vscode/settings.json
  packages/alwatr/LICENSE
  packages/alwatr/README.md
  packages/alwatr/package.json
  packages/alwatr/src/flux.ts
  packages/alwatr/src/fract.ts
  packages/alwatr/src/main.ts
  packages/alwatr/src/nanolib.ts
  packages/alwatr/src/nanotron.ts
  packages/alwatr/src/nitrobase.ts
  packages/alwatr/tsconfig.json
  packages/api/package.json
  packages/api/src/lib/config.ts
  packages/api/src/lib/crypto.ts
  packages/api/src/lib/nitrobase.ts
  packages/api/src/lib/server.ts
  packages/api/tsconfig.json
  yarn.lock
Labels: new-feature

#160 refactor: new folder structures and data model
  packages/app/builder/build.mjs
  packages/app/builder/config.mjs
  packages/app/src/content/data_/env.cjs
  packages/app/src/content/data_/git.cjs
  packages/app/src/content/data_/site.json
  packages/app/src/content/include_/meta.njk
  packages/app/src/content/layout_/base-body.njk
  packages/app/src/content/layout_/base-html.njk
  packages/app/src/content/site.json
  packages/app/src/content/sitemap.xml.data.cjs
  packages/app/src/old/error-404.njk
  packages/app/src/old/fa/chat.njk
  packages/app/src/old/fa/contact.njk
  packages/app/src/old/fa/home.njk
  packages/app/src/old/fa/services.njk
  packages/app/src/old/include/bottom-navigation-bar.njk
  packages/app/src/old/include/navigation-drawer.njk
  packages/app/src/old/layout_/industry.njk
  packages/app/src/old/layout_/service.njk
  packages/app/src/site/content/fa/home.njk
  packages/app/src/site/content/index.data.cjs
  packages/app/src/site/content/misc/error-404.njk
  packages/app/src/site/content/misc/manifest.njk
  packages/app/src/site/content/misc/robots.txt.njk
  packages/app/src/site/content/misc/sitemap.template.js
  packages/app/src/site/data/config.cjs
  packages/app/src/site/include/meta.njk
  packages/app/src/site/include/prerender.template.cjs
  packages/app/src/site/layout/base-body.njk
  packages/app/src/site/layout/base-html.njk
Labels: refactor, breaking-change

#161 feat: new layout styles
  packages/app/src/css/layout/body.css
  packages/app/src/css/layout/config.css
  packages/app/src/css/layout/main-container.css
  packages/app/src/css/main.css
  packages/app/src/old/layout.css
  packages/app/src/site/content/fa/home.njk
  packages/app/src/site/content/index.data.cjs
  packages/app/src/site/data/config.cjs
  packages/app/static/img/person.png
  packages/windstyle/src/base/normalize.css
  packages/windstyle/src/component/page-header.css
  packages/windstyle/src/theme/screen.ts
Labels: new-feature

#162 feat: refactor ts scripts and add lit-elements
  packages/api/package.json
  packages/app/builder/logger.mjs
  packages/app/package.json
  packages/app/src/site/content/fa/home.njk
  packages/app/src/ts/component/greeting.ts
  packages/app/src/ts/lib/config.ts
  packages/app/src/ts/main.ts
  packages/app/src/ts/old/keep-scroll.ts
  packages/app/src/ts/old/lock-scroll.ts
  packages/app/src/ts/old/service-worker.ts
  packages/common/package.json
  packages/windstyle/package.json
  yarn.lock
Labels: new-feature, refactor, breaking-change

#178 feat: remove `alwatr` folder & use `alwatr` package instead.
  packages/alwatr/LICENSE
  packages/alwatr/README.md
  packages/alwatr/package.json
  packages/alwatr/src/flux.ts
  packages/alwatr/src/main.ts
  packages/alwatr/src/nanolib/dedupe.ts
  packages/alwatr/src/nanolib/exit-hook.ts
  packages/alwatr/src/nanolib/nanolib.ts
  packages/alwatr/src/nanolib/node-fs.ts
  packages/alwatr/src/nanotron.ts
  packages/alwatr/src/nitrobase.ts
  packages/alwatr/tsconfig.json
  packages/api/package.json
  packages/api/tsconfig.json
  packages/app/package.json
  packages/app/tsconfig.json
  packages/common/package.json
  yarn.lock
Labels: new-feature

#179 feat: refactor `api` config
  packages/api/src/lib/config.ts
  packages/api/src/lib/nitrobase.ts
  packages/api/src/route/user.ts
  yarn.lock
Labels: new-feature

#182 feat(api): read `host` & `port` from `env` object
  packages/api/src/lib/config.ts
Labels: new-feature

#186 feat(api): use `getEnv` to get `ENV` vars
  packages/api/src/lib/config.ts
Labels: new-feature

#187 feat(api): use `parseBodyAsJson` from `alwatr/nanotron`
  packages/api/src/pre-handler/parse-request-body.ts
  packages/api/src/route/user.ts
Labels: new-feature

#188 feat: update and optimize performances
  packages/app/builder/build.mjs
  packages/app/builder/config.mjs
  packages/app/src/site/include/prerender.template.cjs
  packages/app/src/site/layout/base-body.njk
Labels: new-feature, refactor
